export const data = [
  {
    id: "NHpAGlzrt86KVRfZz6KK",
    link: "",
    name: "veggie chilli",
    ingredients: [
      "aubergine",
      "sweet potato",
      "courgette",
      "mushrooms",
      "kidney beans",
      "chopped tomatoes",
      "garlic",
      "onion",
      "cumin",
      "rice",
    ],
  },
  {
    id: "Nd1TvHTA8V4c7suocTFH",
    link: "",
    name: "chickpea and veg soup",
    ingredients: [
      "onion",
      "garlic",
      "ginger",
      "carrots",
      "green beans",
      "garlic bread",
      "chickpeas",
      "spices",
    ],
  },
  {
    id: "RbfQkeVka5a7l0wMDlJX",
    link: "",
    ingredients: ["pizza", "pizza"],
    name: "pizza",
  },
  {
    id: "S2w17yjCDpQfvi5fGoi0",
    ingredients: [
      "spaghetti",
      "mince",
      "chopped tomatoes",
      "carrots",
      "onion",
      "garlic",
    ],
    name: "Spag bol",
    link: "",
  },
  {
    id: "SwOiD4TNphniyPMeegYH",
    ingredients: [
      "onion",
      "carrots",
      "potatoes",
      "stock",
      "celery",
      "frozen corn",
    ],
    link: "",
    name: "corn chowder",
  },
  {
    id: "T1AyXuQbdLJyS6nW8vBP",
    name: "cauliflower mac n cheese",
    ingredients: [
      "macaroni",
      "cauliflower",
      "cheddar cheese",
      "anchovies",
      "garlic",
      "yoghurt",
      "creme fraiche",
      "pancetta",
      "capers",
      "basil",
      "bread",
      "red wine vinegar",
      "salad",
      "rosemary",
      "dijon mustard",
    ],
    link: "",
  },
  {
    id: "TCzDmB7QQNOx6kUThrah",
    name: "sausage and mash",
    ingredients: [
      "sausages",
      "potatoes",
      "broccoli",
      "green beans",
      "carrots",
      "gravy",
    ],
    link: "",
  },
  {
    id: "afk2yOiu1j1KyYlhddlW",
    name: "berlotti bean soup",
    link: "",
    ingredients: [
      "bacon",
      "berlotti beans",
      "onion",
      "carrots",
      "leek",
      "garlic",
      "chicken stock",
      "bay leaf",
      "rosemary",
      "tomato puree",
      "macaroni",
    ],
  },
  {
    id: "c3zPKlClSqdeMXBLVvMM",
    ingredients: [
      "onion",
      "carrots",
      "potatoes",
      "stock",
      "celery",
      "frozen corn",
    ],
    name: "corn chowder",
    link: "",
  },
  {
    id: "e201LhvoaeUCESXKAYRj",
    link: "",
    ingredients: [
      "sausages",
      "gnocchi",
      "mozzarella",
      "chopped tomatoes",
      "spinach",
      "fennel",
      "garlic",
    ],
    name: "sausage gnocchi bake",
  },
  {
    id: "jpDmGU5kcYhz9Yn9bMcz",
    ingredients: [
      "courgette",
      "aubergine",
      "butternut squash",
      "peppers",
      "onions",
      "cherry tomtatoes",
      "baby potatoes",
      "mushrooms",
      "pittas",
    ],
    name: "roast veg meal",
    link: "",
  },
  {
    id: "lSsyHZzmY3fkhoxBbAx2",
    ingredients: [
      "stuffed pasta",
      "chopped tomatoes",
      "onion",
      "garlic",
      "herbs",
      "pepper",
    ],
    link: "",
    name: "stuffed pasta",
  },
  {
    id: "nWg5hOqkuQzFfscS9WuR",
    ingredients: ["bread", "baked beans", "cheese", "cress", "butter"],
    name: "beans on toast",
    link: "",
  },
  {
    id: "opeLcuEdCnpH00e4ZkGL",
    name: "ginger chicken",
    link: "",
    ingredients: [
      "chicken",
      "garlic",
      "ginger",
      "soy sauce",
      "broccoli",
      "rice",
      "spring onion",
      "leek",
    ],
  },
  {
    id: "s5zIC9lDBMGRpORsCGC2",
    link: "",
    name: "diy nandos",
    ingredients: [
      "chicken thighs",
      "nandos sauce",
      "potatoes",
      "garlic bread",
      "broccoli",
      "green beans",
    ],
  },
  {
    id: "t2ksn5PgeasjmOkhvrKC",
    ingredients: [
      "spaghetti",
      "mince",
      "chopped tomatoes",
      "carrots",
      "onion",
      "garlic",
    ],
    link: "",
    name: "Spag bol",
  },
];
