export const allRecipes = [
  {
    id: "a6xsayr82",
    name: "beans on toast",
    link: "",
    ingredients: ["bread", "baked beans", "cheese", "cress", "butter"],
  },
  {
    id: "pes1j3k22",
    name: "pea pasta salad",
    link: "",
    ingredients: [
      "pasta",
      "broad beans",
      "peas",
      "lemon",
      "feta",
      "spring onion",
      "cherry tomatoes",
    ],
  },
  {
    id: "ygs8p44mu",
    name: "diy nandos",
    link: "",
    ingredients: [
      "chicken thighs",
      "nandos sauce",
      "potatoes",
      "garlic bread",
      "broccoli",
      "green beans",
    ],
  },
  {
    id: "hdhkw77ul",
    name: "berlotti bean soup",
    link: "",
    ingredients: [
      "bacon",
      "berlotti beans",
      "onion",
      "carrots",
      "leek",
      "garlic",
      "chicken stock",
      "bay leaf",
      "rosemary",
      "tomato puree",
      "macaroni",
    ],
  },
  {
    id: "dv5umzfqz",
    name: "sausage and mash",
    link: "",
    ingredients: [
      "sausages",
      "potatoes",
      "broccoli",
      "green beans",
      "carrots",
      "gravy",
    ],
  },
  {
    id: "yw7qmlc2a",
    name: "peanut stew",
    link: "",
    ingredients: [
      "kidney beans",
      "garlic",
      "courgette",
      "rice",
      "cumin",
      "parsley",
      "lemon",
    ],
  },
  {
    id: "1armf6tt0",
    name: "stuffed pasta",
    link: "",
    ingredients: [
      "stuffed pasta",
      "chopped tomatoes",
      "onion",
      "garlic",
      "herbs",
      "pepper",
    ],
  },
  {
    id: "gi6hfyb6x",
    name: "roast veg meal",
    link: "",
    ingredients: [
      "courgette",
      "aubergine",
      "butternut squash",
      "peppers",
      "onions",
      "cherry tomtatoes",
      "baby potatoes",
      "mushrooms",
      "pittas",
    ],
  },
  {
    id: "7xyr46wwe",
    name: "courgette pittas",
    link: "",
    ingredients: [
      "courgette",
      "hummus",
      "tzatziki",
      "pittas",
      "halloumi",
      "paprika",
      "sriracha",
    ],
  },
  {
    id: "8vv70775z",
    name: "ginger chicken",
    link: "",
    ingredients: [
      "chicken",
      "garlic",
      "ginger",
      "soy sauce",
      "broccoli",
      "rice",
      "spring onion",
      "leek",
    ],
  },
  {
    id: "v5ack4g0a",
    name: "keema curry",
    link: "",
    ingredients: [
      "mince meat",
      "peas",
      "sweetcorn",
      "potatoes",
      "onion",
      "garlic",
      "ginger",
      "red chilli",
      "spices",
      "rice",
      "poppadoms",
    ],
  },
  {
    id: "y8yfurzou",
    name: "chickpea and veg soup",
    link: "",
    ingredients: [
      "onion",
      "garlic",
      "ginger",
      "carrots",
      "green beans",
      "garlic bread",
      "chickpeas",
      "spices",
    ],
  },
  {
    id: "ujsg7fco8",
    name: "omelette",
    link: "",
    ingredients: ["eggs", "onion", "cheese", "peppers", "spinach"],
  },
  {
    id: "ziy9e0m0c",
    name: "veggie chilli",
    link: "",
    ingredients: [
      "aubergine",
      "sweet potato",
      "courgette",
      "mushrooms",
      "kidney beans",
      "chopped tomatoes",
      "garlic",
      "onion",
      "cumin",
      "rice",
    ],
  },
  {
    id: "oucj2usi8",
    name: "udon noodle soup",
    link: "",
    ingredients: [
      "noodles",
      "spinach",
      "spring onion",
      "ginger",
      "mushrooms",
      "pork belly",
    ],
  },
  {
    id: "pneu5weh3",
    name: "cauliflower mac n cheese",
    link: "",
    ingredients: [
      "macaroni",
      "cauliflower",
      "cheddar cheese",
      "anchovies",
      "garlic",
      "yoghurt",
      "creme fraiche",
      "pancetta",
      "capers",
      "basil",
      "bread",
      "red wine vinegar",
      "salad",
      "rosemary",
      "dijon mustard",
    ],
  },
  {
    id: "guianvk0t",
    name: "corn chowder",
    link: "",
    ingredients: [
      "onion",
      "carrots",
      "potatoes",
      "stock",
      "celery",
      "frozen corn",
    ],
  },
  {
    id: "kf8dgvuuk",
    name: "Spag bol",
    link: "",
    ingredients: [
      "spaghetti",
      "mince",
      "chopped tomatoes",
      "carrots",
      "onion",
      "garlic",
    ],
  },
  {
    id: "kttwigbf5",
    name: "sausage gnocchi bake",
    link: "",
    ingredients: [
      "sausages",
      "gnocchi",
      "mozzarella",
      "chopped tomatoes",
      "spinach",
      "fennel",
      "garlic",
    ],
  },
];
