export const shoppingList = [
  {
    id: "ers8k2w5k",
    name: "sausage gnocchi bake",
    link: "",
    ingredients: [
      "sausages",
      "gnocchi",
      "mozzarella",
      "chopped tomatoes",
      "spinach",
      "fennel",
      "garlic",
    ],
  },
  {
    id: "jwxsy0dsf",
    name: "Spag bol",
    link: "",
    ingredients: [
      "spaghetti",
      "mince",
      "chopped tomatoes",
      "carrots",
      "onion",
      "garlic",
    ],
  },
  {
    id: "nngcg3fiu",
    name: "diy nandos",
    link: "",
    ingredients: [
      "chicken thighs",
      "nandos sauce",
      "garlic bread",
      "broccoli",
      "green beans",
    ],
  },
  {
    id: "rw9t5os02",
    name: "corn chowder",
    link: "",
    ingredients: [
      "onion",
      "carrots",
      "potatoes",
      "stock",
      "celery",
      "frozen corn",
    ],
  },
  {
    id: "32yuepwk3",
    name: "courgette pittas",
    link: "",
    ingredients: [
      "courgette",
      "hummus",
      "tzatziki",
      "pittas",
      "halloumi",
      "paprika",
      "sriracha",
    ],
  },
  {
    id: "ev3etzdos",
    name: "beans on toast",
    link: "",
    ingredients: ["bread", "baked beans", "cheese", "cress", "butter"],
  },
  {
    id: "ziy9e0m0c",
    name: "veggie chilli",
    link: "",
    ingredients: [],
  },
];
