name: Bump version
on:
  push:
    branches:
      - master
    paths-ignore:
      - "package.json"
      - "CHANGELOG.md"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}
      - name: Automated Version Bump
        uses: phips28/gh-action-bump-version@v8.0.18
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "chore(release): {{version}}"
          target-branch: "master"
          tag-prefix: ""
          minor-wording: 'feat,feature'
          major-wording: 'MAJOR,BREAKING CHANGE,BREAKING CHANGES'
          patch-wording: 'fix,patch,hotfix,bugfix'
